# Arquivo para o Deployment
apiVersion: apps/v1 #versão utilizada da ferramenta;
kind: Deployment # tipo do arquivo (Deployment, Service);
metadata: # descrever algum objeto, inserindo chaves como name;
  name: flask-app-depoyment
spec: # especificações da Aplicação
  replicas: 4 # número de réplicas de Nodes/Pods;
  selector: # para poder nomear as specs, util para aplicações multi-container
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec: # especificações do container que será rodado
      containers: # definir as especificações de containers como: nome e imagem;
        - name: flask
          image: thierry20xx/flask-kube-projeto:2
